development:
  adapter: postgresql
  database: courses
  username: denis
test:
  adapter: postgresql
  database: courses_test
  username: denis
production:
  adapter: postgresql
  database: courses
  username: denis
